spring:
  jpa:
    hibernate:
      # ddl-auto: create # 배포 시는 none 또는 validate 추천
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL, MariaDB
        # dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL
        show_sql: true
        format_sql: true
  # 데이터소스
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver # MySQL, MariaDB
    driver-class-name: org.mariadb.jdbc.Driver # MariaDB
    # driver-class-name: org.postgresql.Driver # PostgreSQL
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}